apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
  labels:
    app: db-noticias
spec:
  template:
    metadata:
      name: db-noticias-deployment
      labels:
        app: db-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
      app: db-noticias

          #env:
      #  - name: MYSQL_ROOT_PASSWORD
      #    value: 
      #      configMapKeyRef:
      #        name: db-configmap
      #        key: MYSQL_ROOT_PASSWORD
