apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: primeiro-volume # inside container
          name: primeiro-pv
  volumes:
   - name: primeiro-volume
     persistentVolumeClain: 
       clainName: pvc-2